### ISSUE TITLE
Update Docker and docker-compose

### ISSUE THREAD

**Issue by citizenrich** [iHRIS/iHRIS#427]
I'm updating the Dockerfile/image and docker-compose. @nobertmn can you have a look at the Dockerfile to see what's wrong?

To reproduce:
```sh
git pull
git checkout update-docker
cd ihris-backend
docker build -t ihris/ihris:$(git rev-parse --short HEAD) .
docker tag ihris/ihris:$(git rev-parse --short HEAD) ihris/ihris
cd ..
docker-compose up
# remember to remove containers/volumes
```

Here's the current error:
```log
ihris     | > @ start /src/ihris-backend/ihris-backend-site
ihris     | > NODE_ENV=production node ./bin/www
ihris     |
ihris     | internal/modules/cjs/loader.js:818
ihris     |   throw err;
ihris     |   ^
ihris     |
ihris     | Error: Cannot find module '/var/lib/iHRIS/ihris-backend/site/package.json'
ihris     | Require stack:
ihris     | - /src/ihris-backend/node_modules/ihrissmartrequire/index.js
ihris     | - /src/ihris-backend/ihris-backend-site/bin/www
ihris     |     at Function.Module._resolveFilename (internal/modules/cjs/loader.js:815:15)
ihris     |     at Function.Module._load (internal/modules/cjs/loader.js:667:27)
ihris     |     at Module.require (internal/modules/cjs/loader.js:887:19)
ihris     |     at require (internal/modules/cjs/helpers.js:74:18)
ihris     |     at Object.<anonymous> (/src/ihris-backend/node_modules/ihrissmartrequire/index.js:10:11)
ihris     |     at Module._compile (internal/modules/cjs/loader.js:999:30)
ihris     |     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
ihris     |     at Module.load (internal/modules/cjs/loader.js:863:32)
ihris     |     at Function.Module._load (internal/modules/cjs/loader.js:708:14)
ihris     |     at Module.require (internal/modules/cjs/loader.js:887:19) {
ihris     |   code: 'MODULE_NOT_FOUND',
ihris     |   requireStack: [
ihris     |     '/src/ihris-backend/node_modules/ihrissmartrequire/index.js',
ihris     |     '/src/ihris-backend/ihris-backend-site/bin/www'
ihris     |   ]
ihris     | }
ihris     | npm ERR! code ELIFECYCLE
ihris     | npm ERR! errno 1
ihris     | npm ERR! @ start: `NODE_ENV=production node ./bin/www`
ihris     | npm ERR! Exit status 1
ihris     | npm ERR!
ihris     | npm ERR! Failed at the @ start script.
ihris     | npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
ihris     |
ihris     | npm ERR! A complete log of this run can be found in:
ihris     | npm ERR!     /root/.npm/_logs/2022-08-25T18_14_09_575Z-debug.log
```

**Comment by citizenrich** [comment]
@ashaban Can you have a look?

**Comment by ashaban** [comment]
@citizenrich you need to set that in the Dockerfile as below
ARG IHRIS_APP__SITE__PATH=/src/ihris-backend/site
ENV IHRIS_APP__SITE__PATH=$IHRIS_APP__SITE__PATH

I also dont see where you are installing the ig files

**Comment by ashaban** [comment]
@citizenrich I have pushed a fix into iHRIS that reads env vars for site and core path. I have also updated Dockerfile to set the site and core path

**Comment by citizenrich** [comment]
This works. Thanks. I'll update more components to versions and keep testing.

**Comment by citizenrich** [comment]
On login, when the user/pass is entered, the login page redirects back to itself and errors:

```
ihris          | /src/ihris-backend/routes/config.js:60
ihris          |         for (let key of Object.keys(nav.menu)) {
ihris          |                                         ^
ihris          |
ihris          | TypeError: Cannot read properties of undefined (reading 'menu')
ihris          |     at filterNavigation (/src/ihris-backend/routes/config.js:60:41)
ihris          |     at /src/ihris-backend/routes/config.js:157:9
ihris          |     at Layer.handle [as handle_request] (/src/ihris-backend/node_modules/express/lib/router/layer.js:95:5)
ihris          |     at next (/src/ihris-backend/node_modules/express/lib/router/route.js:137:13)
ihris          |     at Route.dispatch (/src/ihris-backend/node_modules/express/lib/router/route.js:112:3)
ihris          |     at Layer.handle [as handle_request] (/src/ihris-backend/node_modules/express/lib/router/layer.js:95:5)
ihris          |     at /src/ihris-backend/node_modules/express/lib/router/index.js:281:22
ihris          |     at Function.process_params (/src/ihris-backend/node_modules/express/lib/router/index.js:335:12)
ihris          |     at next (/src/ihris-backend/node_modules/express/lib/router/index.js:275:10)
ihris          |     at Function.handle (/src/ihris-backend/node_modules/express/lib/router/index.js:174:3)
ihris          | No valid key set for configuration Parameters ihris-config
```
Thoughts, @ashaban?
