### ISSUE TITLE
Error in config

### ISSUE THREAD

**Issue by citizenrich** [iHRIS/iHRIS#428]
On startup, there's an error that may need resolution:

```
ihris          | No valid key set for configuration Parameters ihris-config
ihris          | [HPM] Proxy created: /  -> http://kibana:5601
ihris          | (node:29) UnhandledPromiseRejectionWarning: /src/ihris-backend/routes/config.js:1618
ihris          |             userData.phone = user.telecom.find(x => x.system === "phone")?.value;
ihris          |                                                                           ^
ihris          |
ihris          | SyntaxError: Unexpected token '.'
ihris          |     at wrapSafe (internal/modules/cjs/loader.js:915:16)
ihris          |     at Module._compile (internal/modules/cjs/loader.js:963:27)
ihris          |     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
ihris          |     at Module.load (internal/modules/cjs/loader.js:863:32)
ihris          |     at Function.Module._load (internal/modules/cjs/loader.js:708:14)
ihris          |     at Module.require (internal/modules/cjs/loader.js:887:19)
ihris          |     at require (internal/modules/cjs/helpers.js:74:18)
ihris          |     at startUp (/src/ihris-backend/app.js:171:24)
ihris          |     at runMicrotasks (<anonymous>)
ihris          |     at processTicksAndRejections (internal/process/task_queues.js:97:5)
ihris          | (node:29) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 4)
ihris          | (node:29) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by ashaban** [comment]
This is the syntax error due to node version, lets ensure we are not using
an old image of node

**Comment by citizenrich** [comment]
That fixed it.
